### PR TITLE
keypad stuff

### PR DESCRIPTION
**Pull request by frenchie71**

### CODE REVIEW

**Review by omersiar — COMMENTED** [review]
I think TOTP pins can be transferred on unsecured networks, it won't compromise security of TOTP system unless there are millions of samples generated at a time.

**Comment by frenchie71** [comment]
> I think TOTP pins can be transferred on unsecured networks, it won't compromise security of TOTP system unless there are millions of samples generated at a time.

**Comment by frenchie71** [comment]
You are absolutely right Ömer, that is my understanding as well, hence the idea to provide one-time passwords instead of plain pins. At the moment however the PIN itself is transferred in clear text which is bad from a security standpoint; however in my opinion it is better than just transmitting "Open Door" without any type of identification. I delayed the totp implementation because at the time I could not find a lightweight js client which I could then use on the client side for example within nodejs.

**Comment by frenchie71** [comment]
I think what I will be doing the next couple of days is clean up the mess that I have created in my stable branch, then create feature branches (for keypad, magic numbers, log maintenance) and pull requests to your dev branch so that I can go back to mainstream again. In the meanwhile I'd leave the pin in cleartext but prepare everything for totp, e.g. calling a fake subroutine which we may fill at a later time.

**Pull request closed without merging**
